version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: smartlock-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2006
      POSTGRES_DB: smartlock
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  smartlock-app:
    build: .
    container_name: smartlock-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/smartlock
      DB_USERNAME: postgres
      DB_PASSWORD: 2006
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: